[tool.black]
skip-magic-trailing-comma = true
line-length = 139
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | venv
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
force_sort_within_sections = true  # Ensure imports within sections are sorted
known_third_party = ["fastapi", "pydantic"]  # Add third-party modules for isort to identify

[tool.pylint.MASTER]
extension-pkg-allow-list = [
  "pydantic"  # Ensure Pydantic is allowed in FastAPI
]

[tool.pylint.messages_control]
disable = [
  "too-few-public-methods",  # Allows small helper classes without too many methods
  "missing-module-docstring",  # Avoid enforcing docstrings for every module
  "missing-class-docstring",  # Avoid enforcing docstrings for every class
  "missing-function-docstring",  # Avoid enforcing docstrings for small functions
  "W1203",  # Specifically disable the logging f-string warning code
  "W0718", # Disable catching too General Exception
]
enable = ["unused-import", "unused-variable", "invalid-name"]

[tool.pylint.naming]
class-naming-style = "PascalCase"
variable-naming-style = "snake_case"

[tool.pylint.format]
max-line-length = 139  # Ensure pylint's max line length matches Black's setting

[tool.pylint.FORMAT]
expected-line-ending-format = "LF"  # Ensures LF line endings
